version: '3'
services:
  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: accommodation-scoring
    ports:
      - '5432:5432'
