"""Initial create of accommdations and reviews tables

Revision ID: f390c744b6c6
Revises: 
Create Date: 2022-07-03 21:37:00.486410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f390c744b6c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('names', sa.JSON(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('geo', sa.JSON(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('address_street', sa.String(), nullable=True),
    sa.Column('address_zipcode', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_url', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accommodations_id'), 'accommodations', ['id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('accommodation_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('titles', sa.JSON(), nullable=True),
    sa.Column('texts', sa.JSON(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('travel_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('rating_general', sa.Integer(), nullable=True),
    sa.Column('rating_location', sa.Integer(), nullable=True),
    sa.Column('rating_service', sa.Integer(), nullable=True),
    sa.Column('rating_price_quality', sa.Integer(), nullable=True),
    sa.Column('rating_food', sa.Integer(), nullable=True),
    sa.Column('rating_room', sa.Integer(), nullable=True),
    sa.Column('rating_child_friendly', sa.Integer(), nullable=True),
    sa.Column('rating_interior', sa.Integer(), nullable=True),
    sa.Column('rating_size', sa.Integer(), nullable=True),
    sa.Column('rating_activities', sa.Integer(), nullable=True),
    sa.Column('rating_restaurants', sa.Integer(), nullable=True),
    sa.Column('rating_sanitary_state', sa.Integer(), nullable=True),
    sa.Column('rating_accessibility', sa.Integer(), nullable=True),
    sa.Column('rating_nightlife', sa.Integer(), nullable=True),
    sa.Column('rating_culture', sa.Integer(), nullable=True),
    sa.Column('rating_surrounding', sa.Integer(), nullable=True),
    sa.Column('rating_atmosphere', sa.Integer(), nullable=True),
    sa.Column('rating_novice_ski_area', sa.Integer(), nullable=True),
    sa.Column('rating_apres_ski', sa.Integer(), nullable=True),
    sa.Column('rating_beach', sa.Integer(), nullable=True),
    sa.Column('rating_entertainment', sa.Integer(), nullable=True),
    sa.Column('rating_environmental', sa.Integer(), nullable=True),
    sa.Column('rating_pool', sa.Integer(), nullable=True),
    sa.Column('rating_terrace', sa.Integer(), nullable=True),
    sa.Column('rating_housing', sa.Integer(), nullable=True),
    sa.Column('rating_hygiene', sa.Integer(), nullable=True),
    sa.Column('status_published', sa.Boolean(), nullable=True),
    sa.Column('status_checked', sa.Boolean(), nullable=True),
    sa.Column('status_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_accommodation_id'), 'reviews', ['accommodation_id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_accommodation_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_accommodations_id'), table_name='accommodations')
    op.drop_table('accommodations')
    # ### end Alembic commands ###
